
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed May 26 10:47:19 CEST 2021
//----------------------------------------------------

package asint.asc;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int LITCAD = 59;
  public static final int POR = 3;
  public static final int CORCIER = 24;
  public static final int INT = 29;
  public static final int ARRAY = 46;
  public static final int SEPARADOR = 19;
  public static final int WRITE = 52;
  public static final int DELETE = 50;
  public static final int IDENTIFICADOR = 56;
  public static final int NOT = 2;
  public static final int AND = 11;
  public static final int IGUAL = 9;
  public static final int RECORD = 45;
  public static final int TYPE = 55;
  public static final int SQCIER = 22;
  public static final int IGUALDAD = 15;
  public static final int OR = 12;
  public static final int AMPSAND = 28;
  public static final int BOOL = 31;
  public static final int CALL = 44;
  public static final int DIV = 4;
  public static final int LITENT = 57;
  public static final int IF = 37;
  public static final int ENDWHILE = 43;
  public static final int OF = 47;
  public static final int EOF = 0;
  public static final int TRUE = 32;
  public static final int LITREAL = 58;
  public static final int NEW = 49;
  public static final int error = 1;
  public static final int CORAP = 23;
  public static final int COMA = 26;
  public static final int MODULO = 20;
  public static final int MENOS = 14;
  public static final int NULL = 35;
  public static final int MENOR = 5;
  public static final int DESIGUAL = 10;
  public static final int SQAP = 21;
  public static final int MENIG = 7;
  public static final int REAL = 30;
  public static final int MAYOR = 6;
  public static final int PAP = 16;
  public static final int FLECHA = 27;
  public static final int ENDIF = 40;
  public static final int ELSE = 39;
  public static final int PUNTO = 25;
  public static final int MAYIG = 8;
  public static final int NL = 53;
  public static final int READ = 51;
  public static final int WHILE = 41;
  public static final int PCIER = 17;
  public static final int THEN = 38;
  public static final int PUNTOCOM = 18;
  public static final int PROC = 36;
  public static final int STRING = 34;
  public static final int POINTER = 48;
  public static final int FALSE = 33;
  public static final int VAR = 54;
  public static final int DO = 42;
  public static final int MAS = 13;
}

