package alex;

public enum ClaseLexica {
 NOT, POR, DIV, MENOR, MAYOR, MENIG, MAYIG, IGUAL, DESIGUAL, AND, OR, 
 MAS, MENOS, IGUALDAD, PAP, PCIER, PUNTOCOM, SEPARADOR, MODULO, SQAP,
 SQCIER, CORAP, CORCIER, PUNTO, COMA, FLECHA, AMPSAND, INT, REAL,
 BOOL, TRUE, FALSE, STRING, NULL, PROC, IF, THEN, ELSE, ENDIF, WHILE,
 DO, ENDWHILE, CALL, RECORD, ARRAY, OF, POINTER, NEW, DELETE, READ, WRITE,
 NL, VAR, TYPE, IDENTIFICADOR, LITENT, LITREAL, LITCAD, EOF
}
