/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyUnoConstants.java */
package ast.desc;

public interface AnalizadorSintacticoTinyUnoConstants {

  int EOF = 0;
  int letra = 1;
  int digito = 2;
  int dig_nozero = 3;
  int entero = 4;
  int decimal = 5;
  int exponencial = 6;
  int real = 7;
  int Not = 10;
  int And = 11;
  int Or = 12;
  int Int = 13;
  int Realw = 14;
  int Bool = 15;
  int True = 16;
  int False = 17;
  int String = 18;
  int Null = 19;
  int Proc = 20;
  int If = 21;
  int Then = 22;
  int Else = 23;
  int Endif = 24;
  int While = 25;
  int Do = 26;
  int Endwhile = 27;
  int Call = 28;
  int Record = 29;
  int Array = 30;
  int Of = 31;
  int Pointer = 32;
  int New = 33;
  int Delete = 34;
  int Read = 35;
  int Write = 36;
  int Nl = 37;
  int Var = 38;
  int Type = 39;
  int Identificador = 40;
  int LitEnt = 41;
  int LitReal = 42;
  int LitCad = 43;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digito>",
    "<dig_nozero>",
    "<entero>",
    "<decimal>",
    "<exponencial>",
    "<real>",
    "<token of kind 8>",
    "<token of kind 9>",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"string\"",
    "\"null\"",
    "\"proc\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"do\"",
    "\"endwhile\"",
    "\"call\"",
    "\"record\"",
    "\"array\"",
    "\"of\"",
    "\"pointer\"",
    "\"new\"",
    "\"delete\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "\"var\"",
    "\"type\"",
    "<Identificador>",
    "<LitEnt>",
    "<LitReal>",
    "<LitCad>",
    "\"&&\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\".\"",
    "\"->\"",
  };

}
